#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_RELAY_ENABLED
#define AP_RELAY_ENABLED 1
#endif

#if !defined(AP_RELAY_NUM_RELAYS) && CONFIG_HAL_BOARD == HAL_BOARD_SITL
#define AP_RELAY_NUM_RELAYS 16
#endif


#define AP_RELAY_DRONECAN_ENABLED AP_RELAY_ENABLED && HAL_ENABLE_DRONECAN_DRIVERS && !defined(HAL_BUILD_AP_PERIPH)
